# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lastProcessed',
            field=models.DateTimeField(verbose_name='date_published'),
        ),
    ]
