# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170410_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='video',
            name='downloadStatus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='lastProcessed',
            field=models.DateTimeField(null=True, verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='video',
            name='processingStatus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='testResult',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='typeOfProcesses',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
